"""Backward-compatible facade for the split context-builder package."""

from .domains.context_builders import (
    AgentContextBuilder,
    BuiltContext,
    ContextPackingPolicy,
    DEFAULT_PROMPT_PATH,
    SAFE_CONTEXT_MESSAGE_METADATA_KEYS,
    SAFE_CONTEXT_QUOTED_METADATA_KEYS,
    active_game_visible_summary,
    compact_candidate,
    compact_context_value,
    compact_draft,
    compact_game,
    compact_match,
    compact_party,
    compact_requirement,
    compact_tool_payload,
    compact_tool_result_dict,
    reference_duplicate_latest_tool_results,
    context_text_preview,
    message_reference_for_context,
    output_contract,
    planning_contract,
    sanitize_context_media_candidates,
    sanitize_context_observation_summary,
    sanitize_current_message_for_context,
    sanitize_message_metadata_for_context,
    sanitize_quoted_message_metadata_for_context,
    sanitize_resolved_message_reference_for_context,
    tool_result_for_context,
    turn_payload_for_context,
)
from .token_estimation import estimate_tokens

__all__ = [
    "AgentContextBuilder",
    "BuiltContext",
    "ContextPackingPolicy",
    "DEFAULT_PROMPT_PATH",
    "SAFE_CONTEXT_MESSAGE_METADATA_KEYS",
    "SAFE_CONTEXT_QUOTED_METADATA_KEYS",
    "active_game_visible_summary",
    "compact_candidate",
    "compact_context_value",
    "compact_draft",
    "compact_game",
    "compact_match",
    "compact_party",
    "compact_requirement",
    "compact_tool_payload",
    "compact_tool_result_dict",
    "context_text_preview",
    "estimate_tokens",
    "message_reference_for_context",
    "output_contract",
    "planning_contract",
    "reference_duplicate_latest_tool_results",
    "sanitize_context_media_candidates",
    "sanitize_context_observation_summary",
    "sanitize_current_message_for_context",
    "sanitize_message_metadata_for_context",
    "sanitize_quoted_message_metadata_for_context",
    "sanitize_resolved_message_reference_for_context",
    "tool_result_for_context",
    "turn_payload_for_context",
]
