from __future__ import annotations

from typing import Any


def _seed_customer(
    customer_id: str,
    display_name: str,
    preferred_games: list[str],
    preferred_levels: list[str],
    usual_start_hours: list[int],
    smoke_preference: str,
    response_speed: str,
    response_rate: float,
    notes: str,
    *,
    contact: str | None = None,
    usual_party_size: int | None = None,
    usual_party_size_confidence: float | None = None,
) -> dict[str, Any]:
    item: dict[str, Any] = {
        "id": customer_id,
        "display_name": display_name,
        "contact": contact or f"微信备注：{display_name}",
        "preferred_games": preferred_games,
        "preferred_levels": preferred_levels,
        "usual_start_hours": usual_start_hours,
        "smoke_preference": smoke_preference,
        "response_speed": response_speed,
        "response_rate": response_rate,
        "notes": notes,
    }
    if usual_party_size is not None:
        item["usual_party_size"] = usual_party_size
    if usual_party_size_confidence is not None:
        item["usual_party_size_confidence"] = usual_party_size_confidence
    return item


SEED_CUSTOMERS: list[dict[str, Any]] = [
    _seed_customer(
        "zhang",
        "张哥",
        ["杭麻", "川麻"],
        ["0.5", "1", "1-32", "2", "2-64"],
        [14, 15, 19, 20],
        "any",
        "fast",
        0.86,
        "男性；常一个人来；经常打杭麻和川麻；杭麻/财敲常打0.5或1块；川麻常打1块或2块五番封顶，可按1-32/2-64理解；本人抽烟，但也可以打无烟局；财敲响应快。",
        usual_party_size=1,
        usual_party_size_confidence=0.9,
    ),
    _seed_customer(
        "wangjie",
        "王姐",
        ["杭麻", "红中"],
        ["0.5", "1"],
        [13, 14, 15, 18],
        "no_smoke",
        "fast",
        0.78,
        "无烟优先，下午常来。",
        contact="微信备注：王姐无烟",
        usual_party_size=1,
        usual_party_size_confidence=0.8,
    ),
    _seed_customer("chen", "陈姐", ["杭麻", "财敲"], ["0.5"], [14, 15, 16, 19], "no_smoke", "medium", 0.66, "熟人局更愿意来。"),
    _seed_customer("li", "李总", ["川麻", "幺鸡"], ["1-32", "2-16"], [19, 20, 21], "smoke_ok", "medium", 0.58, "最近别问太频繁。"),
    _seed_customer("zhao", "赵哥", ["川麻", "换三张"], ["1-32"], [18, 19, 20], "any", "slow", 0.42, "有空会回，但慢。"),
    _seed_customer("amy", "Amy", ["杭麻", "财敲"], ["0.5"], [17, 18, 19], "no_smoke", "fast", 0.82, "无烟，晚饭后响应好。"),
    _seed_customer("ben", "Ben", ["红中", "湖南麻将"], ["1", "2"], [20, 21, 22], "smoke_ok", "medium", 0.55, "能接受有烟。"),
    _seed_customer("sun", "孙姐", ["杭麻"], ["0.5"], [13, 14, 15], "no_smoke", "medium", 0.61, "下午局优先。"),
    _seed_customer("xu", "徐哥", ["捉鸡", "川麻"], ["1", "2-16"], [19, 20], "any", "fast", 0.74, "川麻也可。"),
    _seed_customer("zhou", "周姐", ["杭麻", "财敲"], ["0.5", "1"], [18, 19], "no_smoke", "fast", 0.8, "不喜欢烟味。"),
    _seed_customer("huang", "黄哥", ["川麻", "定缺"], ["2-16"], [14, 15, 20], "smoke_ok", "medium", 0.52, "川麻 216 可问。"),
    _seed_customer("lin", "林姐", ["红中"], ["368", "0.5"], [13, 14, 18], "no_smoke", "slow", 0.48, "红中老客户。"),
    _seed_customer("gao", "高哥", ["杭麻", "财敲"], ["1"], [20, 21], "any", "medium", 0.57, "晚上 1 档多。"),
    _seed_customer("liu", "刘姐", ["杭麻", "财敲"], ["0.5"], [14, 15, 16], "no_smoke", "fast", 0.72, "下午可重点问。"),
    _seed_customer("ma", "马哥", ["幺鸡", "素鸡", "川麻"], ["1-32", "2-16"], [18, 19, 20], "smoke_ok", "medium", 0.6, "幺鸡可问。"),
    _seed_customer("qian", "钱姐", ["杭麻"], ["0.5"], [19, 20], "no_smoke", "medium", 0.63, "不喜欢太吵。"),
    _seed_customer("feng", "冯哥", ["湖南麻将", "红中"], ["1", "2"], [20, 21], "any", "fast", 0.68, "晚上活跃。"),
    _seed_customer("tang", "唐姐", ["杭麻", "财敲"], ["0.5", "1"], [13, 14, 19], "no_smoke", "medium", 0.59, "熟人局优先。"),
    _seed_customer("wu", "吴哥", ["川麻", "换三张"], ["1-32"], [19, 20, 21], "any", "slow", 0.41, "不急时可问。"),
    _seed_customer("xie", "谢姐", ["杭麻", "红中"], ["0.5"], [14, 15, 18], "no_smoke", "fast", 0.77, "无烟、0.5 响应好。"),
    _seed_customer(
        "mei",
        "梅姐",
        ["杭麻", "财敲"],
        ["0.5"],
        [12, 13, 14],
        "no_smoke",
        "fast",
        0.81,
        "午后局响应好，偏无烟。",
    ),
    _seed_customer("guo", "郭哥", ["川麻", "换三张"], ["2-16", "1-32"], [15, 16, 20], "any", "medium", 0.62, "川麻可约，下午偶尔来。"),
    _seed_customer("du", "杜姐", ["红中", "鲨鱼"], ["368", "568"], [18, 19, 20], "no_smoke", "medium", 0.64, "红中鲨鱼可问，偏无烟。"),
    _seed_customer("jiang", "蒋哥", ["杭麻"], ["1"], [19, 20, 21], "smoke_ok", "fast", 0.73, "晚上 1 档局响应快。"),
    _seed_customer(
        "pan",
        "潘姐",
        ["杭麻", "财敲"],
        ["0.5", "1"],
        [14, 15, 18],
        "no_smoke",
        "fast",
        0.84,
        "熟人无烟局优先。",
        usual_party_size=1,
        usual_party_size_confidence=0.82,
    ),
    _seed_customer("lu", "陆哥", ["川麻", "定缺"], ["1-32"], [20, 21, 22], "smoke_ok", "slow", 0.39, "晚上可问，回复偏慢。"),
    _seed_customer("han", "韩姐", ["杭麻", "红中"], ["0.5"], [13, 14, 19], "no_smoke", "medium", 0.67, "0.5 无烟常客。"),
    _seed_customer("yu", "余哥", ["捉鸡", "川麻"], ["1", "2"], [18, 19], "any", "medium", 0.56, "玩法接受度高。"),
    _seed_customer("bai", "白姐", ["杭麻", "财敲"], ["0.5"], [12, 13, 14, 15], "no_smoke", "fast", 0.79, "下午可优先问。"),
    _seed_customer("shi", "石哥", ["湖南麻将", "红中"], ["1", "2"], [20, 21, 22], "any", "medium", 0.53, "晚场可尝试。"),
    _seed_customer("song", "宋姐", ["杭麻"], ["0.5", "1"], [15, 16, 19], "no_smoke", "medium", 0.65, "不喜欢烟，下午晚些可问。"),
    _seed_customer("luo", "罗哥", ["幺鸡", "幺鸡47", "川麻"], ["1-32", "2-16"], [18, 19, 20], "smoke_ok", "fast", 0.7, "幺鸡47 可优先问。"),
    _seed_customer("deng", "邓姐", ["红中"], ["368"], [14, 15, 18], "no_smoke", "slow", 0.45, "红中 368 可问，别催。"),
    _seed_customer("he", "何哥", ["杭麻", "财敲"], ["1"], [19, 20], "any", "medium", 0.58, "1 档财敲可问。"),
    _seed_customer("cai", "蔡姐", ["杭麻", "财敲"], ["0.5"], [13, 14, 18], "no_smoke", "fast", 0.76, "无烟，熟人局响应更好。"),
    _seed_customer("yao", "姚哥", ["川麻", "换三张", "定缺"], ["2-16"], [20, 21], "smoke_ok", "medium", 0.51, "川麻 216 老玩家。"),
    _seed_customer("kang", "康姐", ["杭麻"], ["0.5", "1"], [16, 17, 18], "no_smoke", "medium", 0.6, "傍晚前后可问。"),
    _seed_customer("qi", "齐哥", ["红中", "湖南麻将"], ["1"], [19, 20, 21], "any", "fast", 0.69, "红中、湖南都可以。"),
    _seed_customer(
        "ran",
        "冉姐",
        ["杭麻", "财敲"],
        ["0.5"],
        [12, 13, 14],
        "no_smoke",
        "fast",
        0.83,
        "中午后响应快。",
    ),
    _seed_customer("pei", "裴哥", ["川麻", "幺鸡"], ["1-32"], [18, 19, 20], "any", "medium", 0.55, "幺鸡普通局可问。"),
    _seed_customer("niu", "牛姐", ["杭麻"], ["0.5"], [15, 16], "no_smoke", "slow", 0.44, "下午偶尔来，不要频繁催。"),
    _seed_customer("tao", "陶哥", ["捉鸡", "川麻"], ["2", "2-16"], [20, 21], "smoke_ok", "medium", 0.57, "大一点的局可问。"),
    _seed_customer("xiong", "熊姐", ["红中", "鲨鱼"], ["368", "568"], [18, 19], "no_smoke", "medium", 0.62, "红中熟人局优先。"),
    _seed_customer("long", "龙哥", ["川麻", "定缺"], ["1-32", "2-16"], [19, 20, 21], "any", "fast", 0.71, "川麻缺人可优先问。"),
    _seed_customer("yan", "严姐", ["杭麻", "财敲"], ["1"], [18, 19], "no_smoke", "medium", 0.61, "1 档无烟财敲可问。"),
    _seed_customer("qiu", "邱哥", ["湖南麻将", "捉鸡"], ["1", "2"], [20, 21, 22], "smoke_ok", "slow", 0.4, "晚场备选。"),
    _seed_customer("an", "安姐", ["杭麻"], ["0.5"], [13, 14, 15, 19], "no_smoke", "fast", 0.75, "0.5 无烟稳定。"),
    _seed_customer("mo", "莫哥", ["川麻", "换三张"], ["1-32"], [18, 19, 20], "any", "medium", 0.59, "川麻换三张可问。"),
    _seed_customer("shao", "邵姐", ["杭麻", "财敲"], ["0.5", "1"], [14, 15, 16], "no_smoke", "medium", 0.64, "下午财敲可问。"),
    _seed_customer("min", "闵哥", ["红中", "川麻"], ["1", "2-16"], [19, 20, 21], "any", "fast", 0.72, "晚上红中、川麻都能问。"),
]
